services:
  db:
    build: .
    image: b2rise_challenge_db
    env_file:
      - .env
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d b2rise_challenge_db"]
      interval: 5s
      timeout: 5s
      retries: 5